version: '3.7'
services:

  leasing-app-backend-service:
    image: nsaro/leasing-app:1.0
    container_name: leasing-app-backend-service
    ports:
      - "8080:8080"
    restart: always
    build:
      context: "."
      dockerfile: "Dockerfile"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/leasingApp?autoReconnect=true&useSSL=false
      RDS_USERNAME: admin
      RDS_PASSWORD: LeasingApp
    depends_on:
      - docker-mysql
    networks:
      - test-network

  docker-mysql:
    image: mysql:latest
    container_name: docker-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: LeasingApp
      MYSQL_PASSWORD: LeasingApp
      MYSQL_DATABASE: leasingApp
      MYSQL_USER: admin
    volumes:
      - ~/apps/mysql:/var/lib/mysql
    networks:
      - test-network

networks:
  test-network:
    driver: bridge
    name: test-network
